name: Show Test Results in Jobs List

on: [push]

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Wait for 5 minutes
        run: sleep 300
  test2:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Wait for 5 minutes
        run: sleep 10

      - name: error
        run: sleep 0/0

      - name: Wait for 5 minutes
        run: sleep 300
